---
- hosts: localhost
  become: yes
  tasks:

    - name: Update apt and upgrade system
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - git
          - curl
          - gnupg
          - unzip
          - software-properties-common
        state: present

    # ========================
    # Docker
    # ========================
    - name: Remove old Docker if exists
      apt:
        name: docker.io
        state: absent

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc

    - name: Add Docker repository
      shell: |
        echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list

    - name: Install Docker CE
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    # ========================
    # kubectl
    # ========================
    - name: Install kubectl (v1.28.2)
      shell: |
        curl -LO "https://dl.k8s.io/release/v1.28.2/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    # ========================
    # Terraform
    # ========================
    - name: Download Terraform 1.6.6
      shell: |
        curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
      args:
        creates: /usr/local/bin/terraform

    - name: Unzip and install Terraform
      shell: |
        unzip terraform.zip
        mv terraform /usr/local/bin/terraform
        rm terraform.zip
      args:
        creates: /usr/local/bin/terraform

    - name: Verify Terraform version
      command: terraform version
