---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt and fix any held packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600  # עדכון חבילות כל שעה

    - name: Remove any existing Docker packages (if any)
      apt:
        name: docker.io
        state: absent

    - name: Install Docker (latest version from Docker's official repo)
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc
        echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Install kubectl (v1.28.2)
      shell: |
        KUBECTL_VERSION="v1.28.2"
        curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
