---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Docker (versioned for Ubuntu 24.04)
      apt:
        name: docker.io=26.1.3-0ubuntu1~24.04.1
        state: present
      register: docker_result
      failed_when: docker_result.failed and ('stderr' in docker_result and 'E:' in docker_result.stderr)

    - name: Install kubectl (v1.28.2)
      shell: |
        KUBECTL_VERSION="v1.28.2"
        curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
