---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt and fix any held packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600  

    - name: Install Docker (latest version for Ubuntu 24.04)
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install kubectl (v1.28.2)
      shell: |
        KUBECTL_VERSION="v1.28.2"
        curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
