name: ci/cd pipline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: action/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Terrafrom
      uses: hashicorp/setup-terraform@v1

    - name: Build Docker Image
      run: |
        docker build -t yakiradela/auth:latest ./services/auth
        docker build -t yakiradela/backend:latest ./services/backend
        docker build -t yakiradela/frontend:latest ./services/frontend

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Images
      run: |
        docker push yakiradela/auth:latest
        docker push yakiradela/backend:latest
        docker push yakiradela/frontend:latest
        
  deploy:
    runs-on: ubunrtu-latest
    needs: build

    steps:

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{  secrets.AWS_ACCESS_KEY_ID }}
        aws-secrets-access-key: ${{  secrets.AWS_SECRETS_ACCESS_KEY  }}
        region: us-east-2
        
    - name: Set up Kubeconfig
      run: |
        aws eks --region us-east-2 update-kubeconfig --name cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/auth-deployment.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/service.yaml
        
